const mockActionPayload = [
  {
    imdb_id: 'tt3794354',
    id: 454626,
    poster_path:
      'https://image.tmdb.org/t/p/w500/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
    title: 'Sonic the Hedgehog',
    overview:
      'Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.',
    vote_average: 7.1,
    genreArr: ['Action', 'Science Fiction', 'Comedy', 'Family'],
    castsArr: [
      'Ben Schwartz',
      'James Marsden',
      'Jim Carrey',
      'Tika Sumpter',
      'Lee Majdoub',
      'Frank C. Turner',
      'Adam Pally',
      'Natasha Rothwell',
      'Neal McDonough',
      'Debs Howard',
      'Bailey Skodje',
      'Lisa Chandler',
      'Elfina Luk',
      'Michael Hogan',
      'Shannon Chan-Kent',
      'Emma Oliver',
      'Dean Petriw',
      'Nicholas Dohy',
      'Melody Nosipho Niemann',
      'Jeanie Cloutier',
      'Jeff Sanca',
      'Steve Warky Nunez',
      'John Flanagan',
      'Bethel Lee',
      'Breanna Watkins',
      'Eleanor Whibley',
      'Jeremy Arnold',
      'Richard David Lecoin',
      'John Specogna',
      "Colleen O'Shaughnessey",
      'Keanu Reeves',
      'Dennis Hopper',
      'Leslie Nielsen',
      'Garry Chalk',
      'Scott Patey',
    ],
    formattedRuntime: '01:39',
  },
  {
    imdb_id: 'tt2076298',
    id: 449924,
    poster_path:
      'https://image.tmdb.org/t/p/w500/yJdeWaVXa2se9agI6B4mQunVYkB.jpg',
    title: 'Ip Man 4: The Finale',
    overview:
      'Following the death of his wife, Ip Man travels to San Francisco to ease tensions between the local kung fu masters and his star student, Bruce Lee, while searching for a better future for his son.',
    vote_average: 5.9,
    genreArr: ['Action', 'Drama', 'History'],
    castsArr: [
      'Donnie Yen',
      'Wu Yue',
      'Vanness Wu',
      'Scott Adkins',
      'Danny Chan Kwok-Kwan',
      'Vanda Lee',
      'Karena Ng',
      'Kent Cheng',
      'Ngo Ka-nin',
      'Lynn Hung',
      'Lo Meng',
      'Mark Strange',
      'Chris Collins',
    ],
    formattedRuntime: '01:45',
  },
  {
    imdb_id: 'tt6673612',
    id: 448119,
    poster_path:
      'https://image.tmdb.org/t/p/w500/5eNiYMu2GXCtNlDwMcJqKGVwyoX.jpg',
    title: 'Dolittle',
    overview:
      'After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria’s England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.',
    vote_average: 6.4,
    genreArr: ['Comedy', 'Fantasy', 'Adventure', 'Family'],
    castsArr: [
      'Robert Downey Jr.',
      'Antonio Banderas',
      'Michael Sheen',
      'Jessie Buckley',
      'Jim Broadbent',
      'Harry Collett',
      'Emma Thompson',
      'Rami Malek',
      'John Cena',
      'Kumail Nanjiani',
      'Octavia Spencer',
      'Tom Holland',
      'Craig Robinson',
      'Ralph Fiennes',
      'Selena Gomez',
      'Marion Cotillard',
      'Frances de la Tour',
      'Ralph Ineson',
      'Tonya Cornelisse',
      'Chris Brazier',
      'Zak Holland',
      'Elliot Barnes-Worrell',
      'Daniel Hoffmann-Gill',
      'Nasir Jama',
      'Carmel Laniado',
      'Stephen Samson',
      'Clive Brunt',
      'Joseph Balderrama',
      'Joseph Segal',
      'Tarik Mesfun',
      'Shane Rawlings',
      'David Cradduck',
      'Michael Herne',
      'Andrew G. Ogleby',
      'Joanna Page',
      'Sonny Ashbourne Serkis',
      'Oliver Chris',
      'Clive Francis',
      'Matt King',
      'Jason Mantzoukas',
      'John-Luke Roberts',
    ],
    formattedRuntime: '01:41',
  },
  {
    imdb_id: 'tt9071322',
    id: 552178,
    poster_path:
      'https://image.tmdb.org/t/p/w500/hJ6YEbrjFvToa5c7IiUqILoB6Je.jpg',
    title: 'Dark Waters',
    overview:
      "A tenacious attorney uncovers a dark secret that connects a growing number of unexplained deaths due to one of the world's largest corporations. In the process, he risks everything — his future, his family, and his own life — to expose the truth.",
    vote_average: 7.5,
    genreArr: ['Drama'],
    castsArr: [
      'Mark Ruffalo',
      'Anne Hathaway',
      'Tim Robbins',
      'Bill Camp',
      'Victor Garber',
      'Mare Winningham',
      'Bill Pullman',
      'William Jackson Harper',
      'Louisa Krause',
      'Scarlett Hicks',
      'Caleb Dwayne Tucker',
      'Ming Wang',
      'Sydney Miles',
      'Kevin Crowley',
      'Annie Fitzpatrick',
      'Denise Dal Vera',
      'Brian Gallagher',
      'John Newberg',
      'Jeffrey Grover',
      'Mike Seely',
      'Marcia Dangerfield',
      'Chaney Morrow',
      'Amy Warner',
      'Kelly Mengelkoch',
    ],
    formattedRuntime: '02:07',
  },
  {
    imdb_id: 'tt5033998',
    id: 458897,
    poster_path:
      'https://image.tmdb.org/t/p/w500/1DPUFG6QnGqzpvEaDEv7TaepycM.jpg',
    title: "Charlie's Angels",
    overview:
      "When a systems engineer blows the whistle on a dangerous technology, Charlie's Angels from across the globe are called into action, putting their lives on the line to protect society.",
    vote_average: 6.4,
    genreArr: ['Action', 'Adventure', 'Comedy'],
    castsArr: [
      'Kristen Stewart',
      'Naomi Scott',
      'Ella Balinska',
      'Elizabeth Banks',
      'Patrick Stewart',
      'Djimon Hounsou',
      'Sam Claflin',
      'Jonathan Tucker',
      'Nat Faxon',
      'Chris Pang',
      'Luis Gerardo Méndez',
      'Noah Centineo',
      'David Schütter',
      'Hannah Hoekstra',
      'Murali Perumal',
      'Michael Strahan',
      'Neil Malik Abdullah',
      'Nick Dong-Sik',
      'Dennenesch Zoudé',
      'Robert Clotworthy',
      'Jaclyn Smith',
      'Danica Patrick',
      'Ronda Rousey',
      'Laverne Cox',
      'Hailee Steinfeld',
      'Chloe Kim',
      'Lili Reinhart',
      'Aly Raisman',
    ],
    formattedRuntime: '01:58',
  },
  {
    imdb_id: 'tt9173418',
    id: 555974,
    poster_path:
      'https://image.tmdb.org/t/p/w500/tIpGQ9uuII7QVFF0GHCFTJFfXve.jpg',
    title: 'Brahms: The Boy II',
    overview:
      'After a family moves into the Heelshire Mansion, their young son soon makes friends with a life-like doll called Brahms.',
    vote_average: 6.1,
    genreArr: ['Horror', 'Mystery', 'Thriller'],
    castsArr: [
      'Katie Holmes',
      'Christopher Convery',
      'Owain Yeoman',
      'Ralph Ineson',
      'Anjali Jay',
      'Oliver Rice',
      'Joely Collins',
      'Natalie Moon',
      'Joanne Kimm',
    ],
    formattedRuntime: '01:26',
  },
  {
    imdb_id: 'tt1634106',
    id: 338762,
    poster_path:
      'https://image.tmdb.org/t/p/w500/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg',
    title: 'Bloodshot',
    overview:
      "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine - Bloodshot. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
    vote_average: 7.3,
    genreArr: ['Action', 'Drama', 'Fantasy', 'Science Fiction'],
    castsArr: [
      'Vin Diesel',
      'Eiza González',
      'Jóhannes Haukur Jóhannesson',
      'Michael Sheen',
      'Toby Kebbell',
      'Sam Heughan',
      'Talulah Riley',
      'Alex Hernandez',
      'Guy Pearce',
      'Siddharth Dhananjay',
      'Lamorne Morris',
      'Maarten Römer',
      'Tamer Burjaq',
      'Patrick Kerton',
      'Ryan Kruger',
      'Alex Anlos',
      'Clyde Berning',
      'Tyrel Meyer',
    ],
    formattedRuntime: '01:50',
  },
  {
    imdb_id: 'tt0983946',
    id: 539537,
    poster_path:
      'https://image.tmdb.org/t/p/w500/yqZdRSC6wfX6AGtBPfGbpvmNKag.jpg',
    title: 'Fantasy Island',
    overview:
      'A group of contest winners arrive at an island hotel to live out their dreams, only to find themselves trapped in nightmare scenarios.',
    vote_average: 4.7,
    genreArr: ['Horror', 'Science Fiction', 'Fantasy'],
    castsArr: [
      'Michael Peña',
      'Maggie Q',
      'Lucy Hale',
      'Austin Stowell',
      'Portia Doubleday',
      'Jimmy O. Yang',
      'Ryan Hansen',
      'Michael Rooker',
      'Parisa Fitz-Henley',
      'Charlotte McKinney',
      'Kim Coates',
      'Goran D. Kleut',
      'Evan Evagora',
      'Joshua Diaz',
      'Steven A. Davis',
      'Tim Wong',
      'Nick Jax Slater',
      'Ian Roberts',
      'Renee Murden',
      'Tane Williams-Accra',
      'Mark Weinhandl',
      'Jeriya Benn',
    ],
    formattedRuntime: '01:49',
  },
  {
    imdb_id: 'tt8722346',
    id: 536743,
    poster_path:
      'https://image.tmdb.org/t/p/w500/ksHdHK17wRKMLkpMH4UslMT1V0p.jpg',
    title: 'Queen & Slim',
    overview:
      'While on a forgettable first date together in Ohio, a black man and a black woman are pulled over for a minor traffic infraction. The situation escalates, with sudden and tragic results, when the man kills the police officer in self-defense. Terrified and in fear for their lives, the man, a retail employee, and the woman, a criminal defense lawyer, are forced to go on the run. But the incident is captured on video and goes viral, and the couple unwittingly become a symbol of trauma, terror, grief and pain for people across the country.',
    vote_average: 7.5,
    genreArr: ['Drama', 'Romance', 'Crime'],
    castsArr: [
      'Daniel Kaluuya',
      'Jodie Turner-Smith',
      'Chloë Sevigny',
      'Bokeem Woodbine',
      'Flea',
      'Indya Moore',
      'Sturgill Simpson',
      "Jahi Di'Allo Winston",
      'Benito Martinez',
      'Melanie Halfkenny',
      'Gralen Bryant Banks',
      'Dickson Obahor',
      'Bryant Tardy',
      'Thom Gossom Jr.',
      'Brian Thornton',
      'Joseph Poliquin',
      'Karen Kaia Livers',
      'Bertrand E. Boyd II',
      'Gregory Keith Granger',
      'Lucky Johnson',
      'Reynolds Washam',
      "Andre De'Sean Shanks",
      'Robert Walker Branchaud',
      'Colby Boothman-Shepard',
      'Andy Dylan',
      'Regina Swanson',
      "Soledad O'Brien",
      'Gayle King',
    ],
    formattedRuntime: '02:11',
  },
  {
    imdb_id: 'tt9214832',
    id: 556678,
    poster_path:
      'https://image.tmdb.org/t/p/w500/sm8iVzA7kRp0d4BSIsgXjsSBMKV.jpg',
    title: 'Emma.',
    overview:
      'In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.',
    vote_average: 7.5,
    genreArr: ['Comedy', 'Drama'],
    castsArr: [
      'Anya Taylor-Joy',
      'Johnny Flynn',
      'Bill Nighy',
      'Mia Goth',
      "Josh O'Connor",
      'Callum Turner',
      'Rupert Graves',
      'Gemma Whelan',
      'Amber Anderson',
      'Tanya Reynolds',
      'Chloe Pirrie',
      'Rose Shalloo',
      'Miranda Hart',
      'Angus Imrie',
      'Nicholas Burns',
      'Oliver Chris',
      'Connor Swindells',
      'Suzie Toase',
      'Myra McFadyen',
      'Esther Coles',
      'Suzy Bloom',
      'Lucy Briers',
      'Anna Francolini',
      'Christopher Godwin',
      'Vanessa Owen',
      'Isis Hainsworth',
      'Hannah Stokely',
      'Charlotte Weston',
    ],
    formattedRuntime: '02:04',
  },
  {
    imdb_id: 'tt3224458',
    id: 501907,
    poster_path:
      'https://image.tmdb.org/t/p/w500/p9vCAVhDK375XyobVcKqzqzsUHE.jpg',
    title: 'A Beautiful Day in the Neighborhood',
    overview:
      "An award-winning cynical journalist, Lloyd Vogel, begrudgingly accepts an assignment to write an Esquire profile piece on the beloved television icon Fred Rogers. After his encounter with Rogers, Vogel's perspective on life is transformed.",
    vote_average: 7.3,
    genreArr: ['Drama'],
    castsArr: [
      'Tom Hanks',
      'Matthew Rhys',
      'Chris Cooper',
      'Susan Kelechi Watson',
      'Enrico Colantoni',
      'Maryann Plunkett',
      'Tammy Blanchard',
      'Wendy Makkena',
      'Christine Lahti',
      'Carmen Cusack',
      'Noah Harpster',
      'Maddie Corman',
      'Joe Fishel',
      'Scott Rapp',
      'Jessica Hecht',
    ],
    formattedRuntime: '01:49',
  },
  {
    imdb_id: 'tt1051906',
    id: 570670,
    poster_path:
      'https://image.tmdb.org/t/p/w500/4U7hpTK0XTQBKT5X60bKmJd05ha.jpg',
    title: 'The Invisible Man',
    overview:
      "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
    vote_average: 0,
    genreArr: ['Horror', 'Science Fiction', 'Thriller'],
    castsArr: [
      'Oliver Jackson-Cohen',
      'Elisabeth Moss',
      'Storm Reid',
      'Aldis Hodge',
      'Harriet Dyer',
      'Amali Golden',
      'Benedict Hardie',
      'Zara Michales',
      'Anthony Brandon Wong',
      'Bianca Pomponio',
      'Dennis Kreusler',
      'Randolph Fields',
      'Sam Smith',
      'Nick Kici',
      'Vivienne Greer',
      'Cleave Williams',
      'Cardwell Lynch',
      'Xavier Fernández',
    ],
    formattedRuntime: '01:50',
  },
  {
    imdb_id: 'tt8613070',
    id: 531428,
    poster_path:
      'https://image.tmdb.org/t/p/w500/3NTEMlG5mQdIAlKDl3AJG0rX29Z.jpg',
    title: 'Portrait of a Lady on Fire',
    overview:
      'On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.',
    vote_average: 8.3,
    genreArr: ['Drama', 'Romance'],
    castsArr: [
      'Noémie Merlant',
      'Adèle Haenel',
      'Luàna Bajrami',
      'Valeria Golino',
      'Christel Baras',
      'Armande Boulanger',
      'Guy Delamarche',
      'Clément Bouyssou',
      'Michèle Clément',
      'Cécile Morel',
    ],
    formattedRuntime: '01:59',
  },
  {
    imdb_id: 'tt5073642',
    id: 548473,
    poster_path:
      'https://image.tmdb.org/t/p/w500/xssWHNrOhAeq0EUzHbHqn1SRb5s.jpg',
    title: 'Color Out of Space',
    overview:
      'The Gardner family moves to a remote farmstead in rural New England to escape the hustle of the 21st century. They are busy adapting to their new life when a meteorite crashes into their front yard, melts into the earth, and infects both the land and the properties of space-time with a strange, otherworldly colour. To their horror, the family discovers this alien force is gradually mutating every life form that it touches—including them.',
    vote_average: 6.6,
    genreArr: ['Horror', 'Science Fiction'],
    castsArr: [
      'Nicolas Cage',
      'Joely Richardson',
      'Madeleine Arthur',
      'Elliot Knight',
      'Tommy Chong',
      'Brendan Meyer',
      'Julian Hilliard',
      'Josh C. Waller',
      "Q'orianka Kilcher",
      'Melissa Nearman',
      'Amanda Booth',
      'Keith Harle',
    ],
    formattedRuntime: '01:51',
  },
  {
    imdb_id: 'tt7798646',
    id: 589049,
    poster_path:
      'https://image.tmdb.org/t/p/w500/cdqZqIcWt0Ne2Io2OA9iWqqMuCA.jpg',
    title: 'The Photograph',
    overview:
      "When famed photographer Christina Eames dies unexpectedly, she leaves her estranged daughter, Mae, hurt, angry and full of questions. When Mae finds a photograph tucked away in a safe-deposit box, she soon finds herself delving into her mother's early life -- an investigation that leads to an unexpected romance with a rising journalist.",
    vote_average: 8.3,
    genreArr: ['Drama', 'Romance'],
    castsArr: [
      'Lakeith Stanfield',
      'Issa Rae',
      'Chelsea Peretti',
      'Courtney B. Vance',
      'Kelvin Harrison Jr.',
      'Kenneth Kynt Bryan',
      'Kingsley Ben-Adir',
      'Teyonah Parris',
      'LilRel Howery',
      'Rob Morgan',
      'Jasmine Cephas Jones',
      "Y'lan Noel",
      'Jamaal Burcher',
      'Wakeema Hollis',
      'Christopher Cassarino',
      'Chanté Adams',
    ],
    formattedRuntime: '01:46',
  },
  {
    imdb_id: 'tt7146812',
    id: 508439,
    poster_path:
      'https://image.tmdb.org/t/p/w500/3VqDLgKLfNYSQYEGC5sjGhcPhn7.jpg',
    title: 'Onward',
    overview:
      'In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.',
    vote_average: 0,
    genreArr: ['Animation', 'Comedy', 'Family', 'Fantasy', 'Adventure'],
    castsArr: [
      'Chris Pratt',
      'Tom Holland',
      'Julia Louis-Dreyfus',
      'Octavia Spencer',
      'Mel Rodriguez',
      'Ali Wong',
      'Lena Waithe',
      'John Ratzenberger',
    ],
    formattedRuntime: '01:43',
  },
  {
    imdb_id: 'tt7549996',
    id: 491283,
    poster_path:
      'https://image.tmdb.org/t/p/w500/iqJhHjD6k6T07waELjMKDpQJUP.jpg',
    title: 'Judy',
    overview:
      'Winter 1968 and showbiz legend Judy Garland arrives in Swinging London to perform a five-week sold-out run at The Talk of the Town. It is 30 years since she shot to global stardom in The Wizard of Oz, but if her voice has weakened, its dramatic intensity has only grown. As she prepares for the show, battles with management, charms musicians and reminisces with friends and adoring fans, her wit and warmth shine through. Even her dreams of love seem undimmed as she embarks on a whirlwind romance with Mickey Deans, her soon-to-be fifth husband.',
    vote_average: 6.9,
    genreArr: ['Drama'],
    castsArr: [
      'Renée Zellweger',
      'Rufus Sewell',
      'Finn Wittrock',
      'Michael Gambon',
      'Richard Cordery',
      'Jessie Buckley',
      'Bella Ramsey',
      'John Dagleish',
      'Gemma-Leah Devereux',
      'Tim Ahern',
      'Bentley Kalu',
      'Arthur McBain',
      'Phil Dunster',
      'David Shields',
      'John Mackay',
      'Darci Shaw',
      'Tom Durant Pritchard',
      'Andy Nyman',
      'Daniel Cerqueira',
      'Royce Pierreson',
      'David Rubin',
      'Natasha Powell',
      'Israel Ruiz',
      'Lucy Russell',
      'Matt Nalton',
    ],
    formattedRuntime: '01:58',
  },
  {
    imdb_id: 'tt4916630',
    id: 522212,
    poster_path:
      'https://image.tmdb.org/t/p/w500/zQGzAoYF6lXDN3L9hxBecQRZIwB.jpg',
    title: 'Just Mercy',
    overview:
      'The powerful true story of Harvard-educated lawyer Bryan Stevenson, who goes to Alabama to defend the disenfranchised and wrongly condemned — including Walter McMillian, a man sentenced to death despite evidence proving his innocence. Bryan fights tirelessly for Walter with the system stacked against them.',
    vote_average: 8.2,
    genreArr: ['Drama', 'History'],
    castsArr: [
      'Michael B. Jordan',
      'Jamie Foxx',
      'Brie Larson',
      "O'Shea Jackson Jr.",
      'Rafe Spall',
      'Rob Morgan',
      'Tim Blake Nelson',
      'Drew Scheid',
      'Steve Coulter',
      'Mary Kraft',
      'Rhoda Griffis',
      'J. Alphonse Nicholson',
      'Karan Kendrick',
      'Tonea Stewart',
      'Hayes Mercure',
      'Lindsay Ayliffe',
      'Drew Scheid',
      'Denitra Isler',
      'Dominic Bogart',
      'Tim Hooper',
      'Andrene Ward-Hammond',
      'John Lacy',
      'Michael Harding',
      'Ron Clinton Smith',
      'C.J. LeBlanc',
      'Elizabeth Becka',
      'Kelly Mumme',
      'Mallory Hoff',
      'Kirk Bovill',
      'Terence Rosemore',
    ],
    formattedRuntime: '02:16',
  },
  {
    imdb_id: 'tt7458762',
    id: 484468,
    poster_path:
      'https://image.tmdb.org/t/p/w500/8bxIzp9w9l9ZzGVwNaIKOaem05A.jpg',
    title: "The Wolf's Call",
    overview:
      "With nuclear war looming, a military expert in underwater acoustics strives to prove things aren't as they seem—or sound—using only his ears.",
    vote_average: 7.7,
    genreArr: ['Thriller', 'Action'],
    castsArr: [
      'François Civil',
      'Omar Sy',
      'Reda Kateb',
      'Mathieu Kassovitz',
      'Paula Beer',
      'Stefan Godin',
      'Alexis Michalik',
      'Jean-Yves Berteloot',
      'Damien Bonnard',
      'Pierre Cevaer',
      'Sébastien Libessart',
      'Paul Granier',
      'Etienne Guillou-Kervern',
      'Guillaume Duhesme',
      'Simon Thomas',
      'Nicolas Van Beveren',
      'Sylvain Loreau',
      'Sébastien Landry',
      'Bastien Ughetto',
      'Brice Ormain',
    ],
    formattedRuntime: '01:55',
  },
  {
    imdb_id: 'tt3513548',
    id: 292011,
    poster_path:
      'https://image.tmdb.org/t/p/w500/8t00sQPe2IgPNLnKmG1EnPUu7Ua.jpg',
    title: 'Richard Jewell',
    overview:
      'Directed by Clint Eastwood and based on true events, "Richard Jewell" is a story of what happens when what is reported as fact obscures the truth. "There is a bomb in Centennial Park. You have thirty minutes." The world is first introduced to Richard Jewell as the security guard who reports finding the device at the 1996 Atlanta bombing-his report making him a hero whose swift actions save countless lives. But within days, the law enforcement wannabe becomes the FBI\'s number one suspect, vilified by press and public alike, his life ripped apart.  Richard Jewell thinks quick, works fast, and saves hundreds, perhaps thousands, of lives after a domestic terrorist plants several pipe bombs and they explode during a concert, only to be falsely suspected of the crime by sloppy FBI work and sensational media coverage.',
    vote_average: 7.4,
    genreArr: ['Drama'],
    castsArr: [
      'Paul Walter Hauser',
      'Sam Rockwell',
      'Kathy Bates',
      'Jon Hamm',
      'Olivia Wilde',
      'Nina Arianda',
      'Ian Gomez',
      'Wayne Duvall',
      'Dylan Kussman',
      'Mike Pniewski',
      'Brandon Stanley',
      'Ryan Boz',
      'Charles Green',
      'Ronnie Allen',
      'David Lengel',
      'Beth Keener',
      'Grant Roberts',
      'Alan Heckner',
      'Desmond Phillips',
      'Alex Collins',
      'Michael Otis',
      'Izzy Herbert',
      'Kelly Collins Lintz',
      'Jonathan D Bergman',
      'Daniel Annone',
      'Zack Shires',
      'Christian Adam',
      'Eric Mendenhall',
      'Randy Havens',
      'Kevin Patrick Murphy',
      'Mitchell Hoog',
      'David Shae',
      'Brian Brightman',
      'David de Vries',
      'Mike Wilson',
      'Megan Mieduch',
      'Andrea Laing',
      'Aubriana Davis',
      'Deja Dee',
      'Franco Castan',
      'Kendrick Cross',
      'Brandon Morris',
      'Billy Slaughter',
      'Philip Fornah',
      'Dani Deetté',
      'John Atwood',
      'Max Bickelhaup',
      'Robert C. Treveiler',
      'Maury Morgan',
      'Tommy Kane',
      'Mallory Hoff',
      'Jill-Michele Meleán',
      'Greg Clarkson',
      'Nicole Sellars',
      'Garon Grigsby',
      'Niko Nicotera',
      'Josh Henry',
      'Jesse Burt',
    ],
    formattedRuntime: '02:12',
  },
]

export default mockActionPayload
