export default function constants() {
  return {
    ERROR: '#e31b12',
    GLOBAL_BLUE: '#2b59c3',
    SUCCESS: '#29a265',
    BLACK: '#263238',
    GREY: '#AAA',
    WHITE: '#ffffff',
    CLOUD_TEXT: 'rgba(38, 50, 56, 0.68)',
    PADDING_LEFT_OF_MAIN_SCREENS: 36,
    SHADOW_COLOR: 'rgba(0, 0, 0,1)',
    COLORS: {
      DEFAULT: '#172B4D',
      SECONDARY: '#F7FAFC',
      INFO: '#11CDEF',
      ERROR: '#F5365C',
      SUCCESS: '#2DCE89',
      WARNING: '#FB6340',
      MUTED: '#ADB5BD',
      INPUT: '#DCDCDC',
      INPUT_SUCCESS: '#7BDEB2',
      INPUT_ERROR: '#FCB3A4',
      PLACEHOLDER: '#9FA5AA',
      GRADIENT_START: '#6B24AA',
      GRADIENT_END: '#AC2688',
      ICON: '#172B4D',
      BORDER: '#CAD1D7',
    },
  }
}
